---
name: Lint Code Base

on: push

jobs:
    super-lint:
        name: Lint Code Base
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Investigation 1
              run: ls -asl

            - name: Investigation 2
              run: ls -asl "$GITHUB_WORKSPACE"

            - name: Investigation 3
              run: echo "$GITHUB_WORKSPACE"

            - name: Lint Code Base
              uses: github/super-linter@v4
              env:
                  DEFAULT_BRANCH: main
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  JAVASCRIPT_DEFAULT_STYLE: prettier
                  LINTER_RULES_PATH: /
                  MARKDOWN_CONFIG_FILE: ./.github/linters/.markdown-lint.yml
                  PYTHON_BLACK_CONFIG_FILE: ./.github/linters/.python-black
                  PYTHON_ISORT_CONFIG_FILE: ./.github/linters/.isort.cfg
                  VALIDATE_YAML: false
